// // Mocks generated by Mockito 5.4.5 from annotations
// // in lmc_app/test/features/teacher_lessons_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i9;
// import 'dart:io' as _i14;

// import 'package:dio/dio.dart' as _i2;
// import 'package:flutter/cupertino.dart' as _i10;
// import 'package:lmc_app/core/di/shared_pref.dart' as _i25;
// import 'package:lmc_app/core/networking/api_service.dart' as _i7;
// import 'package:lmc_app/features/for_all/announsments/data/models/all_announsments.dart'
//     as _i11;
// import 'package:lmc_app/features/for_all/available_courses/data/models/available_courses_model.dart'
//     as _i13;
// import 'package:lmc_app/features/for_all/drawer/drawer_navigations/languages/data/model/language_model.dart'
//     as _i6;
// import 'package:lmc_app/features/for_all/drawer/drawer_navigations/lmc_info/data/model/lmc_info_model.dart'
//     as _i4;
// import 'package:lmc_app/features/for_all/login/data/models/login_response.dart'
//     as _i3;
// import 'package:lmc_app/features/logistic_features/show_tasks/data/models/all_tasks_model.dart'
//     as _i12;
// import 'package:lmc_app/features/student_features/my_courses/show_my_courses/data/models/stu_my_courses_model.dart'
//     as _i20;
// import 'package:lmc_app/features/student_features/notes/data/models/note_model.dart'
//     as _i5;
// import 'package:lmc_app/features/student_features/show_teachers/data/models/teacher_model.dart'
//     as _i19;
// import 'package:lmc_app/features/teacher_features/lessons_management/attendance_and_marks/data/models/course_student_model.dart'
//     as _i23;
// import 'package:lmc_app/features/teacher_features/lessons_management/teacher_flashcards/teacher_flashcards_screen/data/models/teacher_lesson_flashcards_model.dart'
//     as _i16;
// import 'package:lmc_app/features/teacher_features/lessons_management/teacher_selftests/teacher_lesson_selftests_screen/data/models/selftests_model.dart'
//     as _i18;
// import 'package:lmc_app/features/teacher_features/submit_complaint/data/models/my_complaints_model.dart'
//     as _i17;
// import 'package:lmc_app/features/teacher_features/teacher_courses_management/teacher_course_lessons/logic/usecases/teacher_lessons_usescase.dart'
//     as _i24;
// import 'package:lmc_app/features/teacher_features/teacher_courses_management/teacher_courses/data/model/my_courses_teacher_model.dart'
//     as _i15;
// import 'package:mockito/mockito.dart' as _i1;
// import 'package:mockito/src/dummies.dart' as _i8;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: deprecated_member_use
// // ignore_for_file: deprecated_member_use_from_same_package
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: must_be_immutable
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class

// class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
//   _FakeDio_0(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeResponse_1<T> extends _i1.SmartFake implements _i2.Response<T> {
//   _FakeResponse_1(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeUser_2 extends _i1.SmartFake implements _i3.User {
//   _FakeUser_2(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeLmcInfoModel_3 extends _i1.SmartFake implements _i4.LmcInfoModel {
//   _FakeLmcInfoModel_3(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeNoteModel_4 extends _i1.SmartFake implements _i5.NoteModel {
//   _FakeNoteModel_4(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeLanguageModel_5 extends _i1.SmartFake implements _i6.LanguageModel {
//   _FakeLanguageModel_5(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeApiService_6 extends _i1.SmartFake implements _i7.ApiService {
//   _FakeApiService_6(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeBaseOptions_7 extends _i1.SmartFake implements _i2.BaseOptions {
//   _FakeBaseOptions_7(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeHttpClientAdapter_8 extends _i1.SmartFake
//     implements _i2.HttpClientAdapter {
//   _FakeHttpClientAdapter_8(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeTransformer_9 extends _i1.SmartFake implements _i2.Transformer {
//   _FakeTransformer_9(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// class _FakeInterceptors_10 extends _i1.SmartFake implements _i2.Interceptors {
//   _FakeInterceptors_10(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// /// A class which mocks [ApiService].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockApiService extends _i1.Mock implements _i7.ApiService {
//   MockApiService() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i2.Dio get dio => (super.noSuchMethod(
//         Invocation.getter(#dio),
//         returnValue: _FakeDio_0(
//           this,
//           Invocation.getter(#dio),
//         ),
//       ) as _i2.Dio);

//   @override
//   String get baseUrl => (super.noSuchMethod(
//         Invocation.getter(#baseUrl),
//         returnValue: _i8.dummyValue<String>(
//           this,
//           Invocation.getter(#baseUrl),
//         ),
//       ) as String);

//   @override
//   _i9.Future<_i2.Response<dynamic>> login(
//     String? username,
//     String? password,
//     _i10.BuildContext? context,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #login,
//           [
//             username,
//             password,
//             context,
//           ],
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #login,
//             [
//               username,
//               password,
//               context,
//             ],
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> registerGuest(
//     String? name,
//     String? email,
//     String? password,
//     _i10.BuildContext? context,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #registerGuest,
//           [
//             name,
//             email,
//             password,
//             context,
//           ],
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #registerGuest,
//             [
//               name,
//               email,
//               password,
//               context,
//             ],
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<List<_i11.Announcements>> getAllAnnouncements() =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #getAllAnnouncements,
//           [],
//         ),
//         returnValue:
//             _i9.Future<List<_i11.Announcements>>.value(<_i11.Announcements>[]),
//       ) as _i9.Future<List<_i11.Announcements>>);

//   @override
//   _i9.Future<List<_i12.AssignedTasks>> getAllTasks() => (super.noSuchMethod(
//         Invocation.method(
//           #getAllTasks,
//           [],
//         ),
//         returnValue:
//             _i9.Future<List<_i12.AssignedTasks>>.value(<_i12.AssignedTasks>[]),
//       ) as _i9.Future<List<_i12.AssignedTasks>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> markTaskAsDone(
//     int? taskId,
//     _i10.BuildContext? context,
//   ) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #markTaskAsDone,
//           [
//             taskId,
//             context,
//           ],
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #markTaskAsDone,
//             [
//               taskId,
//               context,
//             ],
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<List<_i13.AvailableCourses>> getAvailableCourses({
//     required String? primaryUrl,
//     required String? fallbackUrl,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #getAvailableCourses,
//           [],
//           {
//             #primaryUrl: primaryUrl,
//             #fallbackUrl: fallbackUrl,
//           },
//         ),
//         returnValue: _i9.Future<List<_i13.AvailableCourses>>.value(
//             <_i13.AvailableCourses>[]),
//       ) as _i9.Future<List<_i13.AvailableCourses>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> sendInvoice({
//     required int? taskId,
//     required double? amount,
//     required _i14.File? imageFile,
//     required _i10.BuildContext? context,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #sendInvoice,
//           [],
//           {
//             #taskId: taskId,
//             #amount: amount,
//             #imageFile: imageFile,
//             #context: context,
//           },
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #sendInvoice,
//             [],
//             {
//               #taskId: taskId,
//               #amount: amount,
//               #imageFile: imageFile,
//               #context: context,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> sendTaskToSec({
//     required String? description,
//     required DateTime? deadline,
//     required int? courseId,
//     required int? lessonId,
//     required _i10.BuildContext? context,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #sendTaskToSec,
//           [],
//           {
//             #description: description,
//             #deadline: deadline,
//             #courseId: courseId,
//             #lessonId: lessonId,
//             #context: context,
//           },
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #sendTaskToSec,
//             [],
//             {
//               #description: description,
//               #deadline: deadline,
//               #courseId: courseId,
//               #lessonId: lessonId,
//               #context: context,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<List<_i15.MyCourses>> getTeacherCourses() => (super.noSuchMethod(
//         Invocation.method(
//           #getTeacherCourses,
//           [],
//         ),
//         returnValue: _i9.Future<List<_i15.MyCourses>>.value(<_i15.MyCourses>[]),
//       ) as _i9.Future<List<_i15.MyCourses>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> AddFlashcard({
//     required int? lessonId,
//     required String? content,
//     required String? translation,
//     required _i10.BuildContext? context,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #AddFlashcard,
//           [],
//           {
//             #lessonId: lessonId,
//             #content: content,
//             #translation: translation,
//             #context: context,
//           },
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #AddFlashcard,
//             [],
//             {
//               #lessonId: lessonId,
//               #content: content,
//               #translation: translation,
//               #context: context,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> AddSelfTest({
//     required int? lessonId,
//     required String? title,
//     required String? description,
//     required _i10.BuildContext? context,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #AddSelfTest,
//           [],
//           {
//             #lessonId: lessonId,
//             #title: title,
//             #description: description,
//             #context: context,
//           },
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #AddSelfTest,
//             [],
//             {
//               #lessonId: lessonId,
//               #title: title,
//               #description: description,
//               #context: context,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> AddSelfTestQuestion({
//     required int? selfTestId,
//     _i14.File? media,
//     required String? questionText,
//     required String? type,
//     List<String>? choices,
//     required String? correctAnswer,
//     required _i10.BuildContext? context,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #AddSelfTestQuestion,
//           [],
//           {
//             #selfTestId: selfTestId,
//             #media: media,
//             #questionText: questionText,
//             #type: type,
//             #choices: choices,
//             #correctAnswer: correctAnswer,
//             #context: context,
//           },
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #AddSelfTestQuestion,
//             [],
//             {
//               #selfTestId: selfTestId,
//               #media: media,
//               #questionText: questionText,
//               #type: type,
//               #choices: choices,
//               #correctAnswer: correctAnswer,
//               #context: context,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> EditFlashcard({
//     required int? flashcardId,
//     required String? content,
//     required String? translation,
//     required _i10.BuildContext? context,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #EditFlashcard,
//           [],
//           {
//             #flashcardId: flashcardId,
//             #content: content,
//             #translation: translation,
//             #context: context,
//           },
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #EditFlashcard,
//             [],
//             {
//               #flashcardId: flashcardId,
//               #content: content,
//               #translation: translation,
//               #context: context,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> DeleteFlashcard({
//     required int? flashcardId,
//     required _i10.BuildContext? context,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #DeleteFlashcard,
//           [],
//           {
//             #flashcardId: flashcardId,
//             #context: context,
//           },
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #DeleteFlashcard,
//             [],
//             {
//               #flashcardId: flashcardId,
//               #context: context,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<List<_i16.FlashCards>> getTeacherLessonFlashcards(int? lessonId) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #getTeacherLessonFlashcards,
//           [lessonId],
//         ),
//         returnValue:
//             _i9.Future<List<_i16.FlashCards>>.value(<_i16.FlashCards>[]),
//       ) as _i9.Future<List<_i16.FlashCards>>);

//   @override
//   _i9.Future<List<_i17.Data>> getTeacherComplaints() => (super.noSuchMethod(
//         Invocation.method(
//           #getTeacherComplaints,
//           [],
//         ),
//         returnValue: _i9.Future<List<_i17.Data>>.value(<_i17.Data>[]),
//       ) as _i9.Future<List<_i17.Data>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> SubmitComplaint({
//     required String? subject,
//     required _i10.BuildContext? context,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #SubmitComplaint,
//           [],
//           {
//             #subject: subject,
//             #context: context,
//           },
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #SubmitComplaint,
//             [],
//             {
//               #subject: subject,
//               #context: context,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> deleteComplaint(String? complaintId) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #deleteComplaint,
//           [complaintId],
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #deleteComplaint,
//             [complaintId],
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> EditComplaint({
//     required String? subject,
//     required String? complaintId,
//     required _i10.BuildContext? context,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #EditComplaint,
//           [],
//           {
//             #subject: subject,
//             #complaintId: complaintId,
//             #context: context,
//           },
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #EditComplaint,
//             [],
//             {
//               #subject: subject,
//               #complaintId: complaintId,
//               #context: context,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<List<_i18.SelfTests>> getSelfTests(int? lessonId) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #getSelfTests,
//           [lessonId],
//         ),
//         returnValue: _i9.Future<List<_i18.SelfTests>>.value(<_i18.SelfTests>[]),
//       ) as _i9.Future<List<_i18.SelfTests>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> markAttendance({
//     required int? lessonId,
//     required int? studentId,
//     required _i10.BuildContext? context,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #markAttendance,
//           [],
//           {
//             #lessonId: lessonId,
//             #studentId: studentId,
//             #context: context,
//           },
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #markAttendance,
//             [],
//             {
//               #lessonId: lessonId,
//               #studentId: studentId,
//               #context: context,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> enterBonus({
//     required int? lessonId,
//     required int? studentId,
//     required double? bonus,
//     required _i10.BuildContext? context,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #enterBonus,
//           [],
//           {
//             #lessonId: lessonId,
//             #studentId: studentId,
//             #bonus: bonus,
//             #context: context,
//           },
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #enterBonus,
//             [],
//             {
//               #lessonId: lessonId,
//               #studentId: studentId,
//               #bonus: bonus,
//               #context: context,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<List<_i19.Teachers>> getTeachersList() => (super.noSuchMethod(
//         Invocation.method(
//           #getTeachersList,
//           [],
//         ),
//         returnValue: _i9.Future<List<_i19.Teachers>>.value(<_i19.Teachers>[]),
//       ) as _i9.Future<List<_i19.Teachers>>);

//   @override
//   _i9.Future<List<_i20.MyCoursesStu>> getStudentMyCourses() =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #getStudentMyCourses,
//           [],
//         ),
//         returnValue:
//             _i9.Future<List<_i20.MyCoursesStu>>.value(<_i20.MyCoursesStu>[]),
//       ) as _i9.Future<List<_i20.MyCoursesStu>>);

//   @override
//   _i9.Future<List<_i21.Lesson>> getLessons(int? courseId) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #getLessons,
//           [courseId],
//         ),
//         returnValue: _i9.Future<List<_i21.Lesson>>.value(<_i21.Lesson>[]),
//       ) as _i9.Future<List<_i21.Lesson>>);

//   @override
//   _i9.Future<List<_i22.Lessons>> getTeacherLessons(int? courseId) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #getTeacherLessons,
//           [courseId],
//         ),
//         returnValue: _i9.Future<List<_i22.Lessons>>.value(<_i22.Lessons>[]),
//       ) as _i9.Future<List<_i22.Lessons>>);

//   @override
//   _i9.Future<_i3.User> getUserName() => (super.noSuchMethod(
//         Invocation.method(
//           #getUserName,
//           [],
//         ),
//         returnValue: _i9.Future<_i3.User>.value(_FakeUser_2(
//           this,
//           Invocation.method(
//             #getUserName,
//             [],
//           ),
//         )),
//       ) as _i9.Future<_i3.User>);

//   @override
//   _i9.Future<_i4.LmcInfoModel> getLmcInfo() => (super.noSuchMethod(
//         Invocation.method(
//           #getLmcInfo,
//           [],
//         ),
//         returnValue: _i9.Future<_i4.LmcInfoModel>.value(_FakeLmcInfoModel_3(
//           this,
//           Invocation.method(
//             #getLmcInfo,
//             [],
//           ),
//         )),
//       ) as _i9.Future<_i4.LmcInfoModel>);

//   @override
//   _i9.Future<bool> addNote(_i5.Notes? note) => (super.noSuchMethod(
//         Invocation.method(
//           #addNote,
//           [note],
//         ),
//         returnValue: _i9.Future<bool>.value(false),
//       ) as _i9.Future<bool>);

//   @override
//   _i9.Future<_i5.NoteModel> getNotes() => (super.noSuchMethod(
//         Invocation.method(
//           #getNotes,
//           [],
//         ),
//         returnValue: _i9.Future<_i5.NoteModel>.value(_FakeNoteModel_4(
//           this,
//           Invocation.method(
//             #getNotes,
//             [],
//           ),
//         )),
//       ) as _i9.Future<_i5.NoteModel>);

//   @override
//   _i9.Future<bool> deleteNote(int? noteId) => (super.noSuchMethod(
//         Invocation.method(
//           #deleteNote,
//           [noteId],
//         ),
//         returnValue: _i9.Future<bool>.value(false),
//       ) as _i9.Future<bool>);

//   @override
//   _i9.Future<bool> editNote(_i5.Notes? note) => (super.noSuchMethod(
//         Invocation.method(
//           #editNote,
//           [note],
//         ),
//         returnValue: _i9.Future<bool>.value(false),
//       ) as _i9.Future<bool>);

//   @override
//   _i9.Future<_i6.LanguageModel> getAllLanguages() => (super.noSuchMethod(
//         Invocation.method(
//           #getAllLanguages,
//           [],
//         ),
//         returnValue: _i9.Future<_i6.LanguageModel>.value(_FakeLanguageModel_5(
//           this,
//           Invocation.method(
//             #getAllLanguages,
//             [],
//           ),
//         )),
//       ) as _i9.Future<_i6.LanguageModel>);

//   @override
//   _i9.Future<List<_i23.Students>> getCourseStudents(int? lessonId) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #getCourseStudents,
//           [lessonId],
//         ),
//         returnValue: _i9.Future<List<_i23.Students>>.value(<_i23.Students>[]),
//       ) as _i9.Future<List<_i23.Students>>);
// }

// /// A class which mocks [GetTeacherLessonsUsecase].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockGetTeacherLessonsUsecase extends _i1.Mock
//     implements _i24.GetTeacherLessonsUsecase {
//   MockGetTeacherLessonsUsecase() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i7.ApiService get apiService => (super.noSuchMethod(
//         Invocation.getter(#apiService),
//         returnValue: _FakeApiService_6(
//           this,
//           Invocation.getter(#apiService),
//         ),
//       ) as _i7.ApiService);

//   @override
//   _i9.Future<List<_i22.Lessons>> execute(int? courseId) => (super.noSuchMethod(
//         Invocation.method(
//           #execute,
//           [courseId],
//         ),
//         returnValue: _i9.Future<List<_i22.Lessons>>.value(<_i22.Lessons>[]),
//       ) as _i9.Future<List<_i22.Lessons>>);
// }

// /// A class which mocks [Dio].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockDio extends _i1.Mock implements _i2.Dio {
//   MockDio() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i2.BaseOptions get options => (super.noSuchMethod(
//         Invocation.getter(#options),
//         returnValue: _FakeBaseOptions_7(
//           this,
//           Invocation.getter(#options),
//         ),
//       ) as _i2.BaseOptions);

//   @override
//   set options(_i2.BaseOptions? _options) => super.noSuchMethod(
//         Invocation.setter(
//           #options,
//           _options,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i2.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
//         Invocation.getter(#httpClientAdapter),
//         returnValue: _FakeHttpClientAdapter_8(
//           this,
//           Invocation.getter(#httpClientAdapter),
//         ),
//       ) as _i2.HttpClientAdapter);

//   @override
//   set httpClientAdapter(_i2.HttpClientAdapter? _httpClientAdapter) =>
//       super.noSuchMethod(
//         Invocation.setter(
//           #httpClientAdapter,
//           _httpClientAdapter,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i2.Transformer get transformer => (super.noSuchMethod(
//         Invocation.getter(#transformer),
//         returnValue: _FakeTransformer_9(
//           this,
//           Invocation.getter(#transformer),
//         ),
//       ) as _i2.Transformer);

//   @override
//   set transformer(_i2.Transformer? _transformer) => super.noSuchMethod(
//         Invocation.setter(
//           #transformer,
//           _transformer,
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i2.Interceptors get interceptors => (super.noSuchMethod(
//         Invocation.getter(#interceptors),
//         returnValue: _FakeInterceptors_10(
//           this,
//           Invocation.getter(#interceptors),
//         ),
//       ) as _i2.Interceptors);

//   @override
//   void close({bool? force = false}) => super.noSuchMethod(
//         Invocation.method(
//           #close,
//           [],
//           {#force: force},
//         ),
//         returnValueForMissingStub: null,
//       );

//   @override
//   _i9.Future<_i2.Response<T>> head<T>(
//     String? path, {
//     Object? data,
//     Map<String, dynamic>? queryParameters,
//     _i2.Options? options,
//     _i2.CancelToken? cancelToken,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #head,
//           [path],
//           {
//             #data: data,
//             #queryParameters: queryParameters,
//             #options: options,
//             #cancelToken: cancelToken,
//           },
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #head,
//             [path],
//             {
//               #data: data,
//               #queryParameters: queryParameters,
//               #options: options,
//               #cancelToken: cancelToken,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i9.Future<_i2.Response<T>> headUri<T>(
//     Uri? uri, {
//     Object? data,
//     _i2.Options? options,
//     _i2.CancelToken? cancelToken,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #headUri,
//           [uri],
//           {
//             #data: data,
//             #options: options,
//             #cancelToken: cancelToken,
//           },
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #headUri,
//             [uri],
//             {
//               #data: data,
//               #options: options,
//               #cancelToken: cancelToken,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i9.Future<_i2.Response<T>> get<T>(
//     String? path, {
//     Object? data,
//     Map<String, dynamic>? queryParameters,
//     _i2.Options? options,
//     _i2.CancelToken? cancelToken,
//     _i2.ProgressCallback? onReceiveProgress,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #get,
//           [path],
//           {
//             #data: data,
//             #queryParameters: queryParameters,
//             #options: options,
//             #cancelToken: cancelToken,
//             #onReceiveProgress: onReceiveProgress,
//           },
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #get,
//             [path],
//             {
//               #data: data,
//               #queryParameters: queryParameters,
//               #options: options,
//               #cancelToken: cancelToken,
//               #onReceiveProgress: onReceiveProgress,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i9.Future<_i2.Response<T>> getUri<T>(
//     Uri? uri, {
//     Object? data,
//     _i2.Options? options,
//     _i2.CancelToken? cancelToken,
//     _i2.ProgressCallback? onReceiveProgress,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #getUri,
//           [uri],
//           {
//             #data: data,
//             #options: options,
//             #cancelToken: cancelToken,
//             #onReceiveProgress: onReceiveProgress,
//           },
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #getUri,
//             [uri],
//             {
//               #data: data,
//               #options: options,
//               #cancelToken: cancelToken,
//               #onReceiveProgress: onReceiveProgress,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i9.Future<_i2.Response<T>> post<T>(
//     String? path, {
//     Object? data,
//     Map<String, dynamic>? queryParameters,
//     _i2.Options? options,
//     _i2.CancelToken? cancelToken,
//     _i2.ProgressCallback? onSendProgress,
//     _i2.ProgressCallback? onReceiveProgress,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #post,
//           [path],
//           {
//             #data: data,
//             #queryParameters: queryParameters,
//             #options: options,
//             #cancelToken: cancelToken,
//             #onSendProgress: onSendProgress,
//             #onReceiveProgress: onReceiveProgress,
//           },
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #post,
//             [path],
//             {
//               #data: data,
//               #queryParameters: queryParameters,
//               #options: options,
//               #cancelToken: cancelToken,
//               #onSendProgress: onSendProgress,
//               #onReceiveProgress: onReceiveProgress,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i9.Future<_i2.Response<T>> postUri<T>(
//     Uri? uri, {
//     Object? data,
//     _i2.Options? options,
//     _i2.CancelToken? cancelToken,
//     _i2.ProgressCallback? onSendProgress,
//     _i2.ProgressCallback? onReceiveProgress,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #postUri,
//           [uri],
//           {
//             #data: data,
//             #options: options,
//             #cancelToken: cancelToken,
//             #onSendProgress: onSendProgress,
//             #onReceiveProgress: onReceiveProgress,
//           },
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #postUri,
//             [uri],
//             {
//               #data: data,
//               #options: options,
//               #cancelToken: cancelToken,
//               #onSendProgress: onSendProgress,
//               #onReceiveProgress: onReceiveProgress,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i9.Future<_i2.Response<T>> put<T>(
//     String? path, {
//     Object? data,
//     Map<String, dynamic>? queryParameters,
//     _i2.Options? options,
//     _i2.CancelToken? cancelToken,
//     _i2.ProgressCallback? onSendProgress,
//     _i2.ProgressCallback? onReceiveProgress,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #put,
//           [path],
//           {
//             #data: data,
//             #queryParameters: queryParameters,
//             #options: options,
//             #cancelToken: cancelToken,
//             #onSendProgress: onSendProgress,
//             #onReceiveProgress: onReceiveProgress,
//           },
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #put,
//             [path],
//             {
//               #data: data,
//               #queryParameters: queryParameters,
//               #options: options,
//               #cancelToken: cancelToken,
//               #onSendProgress: onSendProgress,
//               #onReceiveProgress: onReceiveProgress,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i9.Future<_i2.Response<T>> putUri<T>(
//     Uri? uri, {
//     Object? data,
//     _i2.Options? options,
//     _i2.CancelToken? cancelToken,
//     _i2.ProgressCallback? onSendProgress,
//     _i2.ProgressCallback? onReceiveProgress,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #putUri,
//           [uri],
//           {
//             #data: data,
//             #options: options,
//             #cancelToken: cancelToken,
//             #onSendProgress: onSendProgress,
//             #onReceiveProgress: onReceiveProgress,
//           },
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #putUri,
//             [uri],
//             {
//               #data: data,
//               #options: options,
//               #cancelToken: cancelToken,
//               #onSendProgress: onSendProgress,
//               #onReceiveProgress: onReceiveProgress,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i9.Future<_i2.Response<T>> patch<T>(
//     String? path, {
//     Object? data,
//     Map<String, dynamic>? queryParameters,
//     _i2.Options? options,
//     _i2.CancelToken? cancelToken,
//     _i2.ProgressCallback? onSendProgress,
//     _i2.ProgressCallback? onReceiveProgress,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #patch,
//           [path],
//           {
//             #data: data,
//             #queryParameters: queryParameters,
//             #options: options,
//             #cancelToken: cancelToken,
//             #onSendProgress: onSendProgress,
//             #onReceiveProgress: onReceiveProgress,
//           },
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #patch,
//             [path],
//             {
//               #data: data,
//               #queryParameters: queryParameters,
//               #options: options,
//               #cancelToken: cancelToken,
//               #onSendProgress: onSendProgress,
//               #onReceiveProgress: onReceiveProgress,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i9.Future<_i2.Response<T>> patchUri<T>(
//     Uri? uri, {
//     Object? data,
//     _i2.Options? options,
//     _i2.CancelToken? cancelToken,
//     _i2.ProgressCallback? onSendProgress,
//     _i2.ProgressCallback? onReceiveProgress,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #patchUri,
//           [uri],
//           {
//             #data: data,
//             #options: options,
//             #cancelToken: cancelToken,
//             #onSendProgress: onSendProgress,
//             #onReceiveProgress: onReceiveProgress,
//           },
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #patchUri,
//             [uri],
//             {
//               #data: data,
//               #options: options,
//               #cancelToken: cancelToken,
//               #onSendProgress: onSendProgress,
//               #onReceiveProgress: onReceiveProgress,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i9.Future<_i2.Response<T>> delete<T>(
//     String? path, {
//     Object? data,
//     Map<String, dynamic>? queryParameters,
//     _i2.Options? options,
//     _i2.CancelToken? cancelToken,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #delete,
//           [path],
//           {
//             #data: data,
//             #queryParameters: queryParameters,
//             #options: options,
//             #cancelToken: cancelToken,
//           },
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #delete,
//             [path],
//             {
//               #data: data,
//               #queryParameters: queryParameters,
//               #options: options,
//               #cancelToken: cancelToken,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i9.Future<_i2.Response<T>> deleteUri<T>(
//     Uri? uri, {
//     Object? data,
//     _i2.Options? options,
//     _i2.CancelToken? cancelToken,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #deleteUri,
//           [uri],
//           {
//             #data: data,
//             #options: options,
//             #cancelToken: cancelToken,
//           },
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #deleteUri,
//             [uri],
//             {
//               #data: data,
//               #options: options,
//               #cancelToken: cancelToken,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> download(
//     String? urlPath,
//     dynamic savePath, {
//     _i2.ProgressCallback? onReceiveProgress,
//     Map<String, dynamic>? queryParameters,
//     _i2.CancelToken? cancelToken,
//     bool? deleteOnError = true,
//     _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
//     String? lengthHeader = 'content-length',
//     Object? data,
//     _i2.Options? options,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #download,
//           [
//             urlPath,
//             savePath,
//           ],
//           {
//             #onReceiveProgress: onReceiveProgress,
//             #queryParameters: queryParameters,
//             #cancelToken: cancelToken,
//             #deleteOnError: deleteOnError,
//             #fileAccessMode: fileAccessMode,
//             #lengthHeader: lengthHeader,
//             #data: data,
//             #options: options,
//           },
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #download,
//             [
//               urlPath,
//               savePath,
//             ],
//             {
//               #onReceiveProgress: onReceiveProgress,
//               #queryParameters: queryParameters,
//               #cancelToken: cancelToken,
//               #deleteOnError: deleteOnError,
//               #fileAccessMode: fileAccessMode,
//               #lengthHeader: lengthHeader,
//               #data: data,
//               #options: options,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<_i2.Response<dynamic>> downloadUri(
//     Uri? uri,
//     dynamic savePath, {
//     _i2.ProgressCallback? onReceiveProgress,
//     _i2.CancelToken? cancelToken,
//     bool? deleteOnError = true,
//     _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
//     String? lengthHeader = 'content-length',
//     Object? data,
//     _i2.Options? options,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #downloadUri,
//           [
//             uri,
//             savePath,
//           ],
//           {
//             #onReceiveProgress: onReceiveProgress,
//             #cancelToken: cancelToken,
//             #deleteOnError: deleteOnError,
//             #fileAccessMode: fileAccessMode,
//             #lengthHeader: lengthHeader,
//             #data: data,
//             #options: options,
//           },
//         ),
//         returnValue:
//             _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
//           this,
//           Invocation.method(
//             #downloadUri,
//             [
//               uri,
//               savePath,
//             ],
//             {
//               #onReceiveProgress: onReceiveProgress,
//               #cancelToken: cancelToken,
//               #deleteOnError: deleteOnError,
//               #fileAccessMode: fileAccessMode,
//               #lengthHeader: lengthHeader,
//               #data: data,
//               #options: options,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<dynamic>>);

//   @override
//   _i9.Future<_i2.Response<T>> request<T>(
//     String? url, {
//     Object? data,
//     Map<String, dynamic>? queryParameters,
//     _i2.CancelToken? cancelToken,
//     _i2.Options? options,
//     _i2.ProgressCallback? onSendProgress,
//     _i2.ProgressCallback? onReceiveProgress,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #request,
//           [url],
//           {
//             #data: data,
//             #queryParameters: queryParameters,
//             #cancelToken: cancelToken,
//             #options: options,
//             #onSendProgress: onSendProgress,
//             #onReceiveProgress: onReceiveProgress,
//           },
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #request,
//             [url],
//             {
//               #data: data,
//               #queryParameters: queryParameters,
//               #cancelToken: cancelToken,
//               #options: options,
//               #onSendProgress: onSendProgress,
//               #onReceiveProgress: onReceiveProgress,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i9.Future<_i2.Response<T>> requestUri<T>(
//     Uri? uri, {
//     Object? data,
//     _i2.CancelToken? cancelToken,
//     _i2.Options? options,
//     _i2.ProgressCallback? onSendProgress,
//     _i2.ProgressCallback? onReceiveProgress,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #requestUri,
//           [uri],
//           {
//             #data: data,
//             #cancelToken: cancelToken,
//             #options: options,
//             #onSendProgress: onSendProgress,
//             #onReceiveProgress: onReceiveProgress,
//           },
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #requestUri,
//             [uri],
//             {
//               #data: data,
//               #cancelToken: cancelToken,
//               #options: options,
//               #onSendProgress: onSendProgress,
//               #onReceiveProgress: onReceiveProgress,
//             },
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i9.Future<_i2.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #fetch,
//           [requestOptions],
//         ),
//         returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_1<T>(
//           this,
//           Invocation.method(
//             #fetch,
//             [requestOptions],
//           ),
//         )),
//       ) as _i9.Future<_i2.Response<T>>);

//   @override
//   _i2.Dio clone({
//     _i2.BaseOptions? options,
//     _i2.Interceptors? interceptors,
//     _i2.HttpClientAdapter? httpClientAdapter,
//     _i2.Transformer? transformer,
//   }) =>
//       (super.noSuchMethod(
//         Invocation.method(
//           #clone,
//           [],
//           {
//             #options: options,
//             #interceptors: interceptors,
//             #httpClientAdapter: httpClientAdapter,
//             #transformer: transformer,
//           },
//         ),
//         returnValue: _FakeDio_0(
//           this,
//           Invocation.method(
//             #clone,
//             [],
//             {
//               #options: options,
//               #interceptors: interceptors,
//               #httpClientAdapter: httpClientAdapter,
//               #transformer: transformer,
//             },
//           ),
//         ),
//       ) as _i2.Dio);
// }

// /// A class which mocks [LocalStorage].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockLocalStorage extends _i1.Mock implements _i25.LocalStorage {
//   MockLocalStorage() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i9.Future<void> saveToken(String? token) => (super.noSuchMethod(
//         Invocation.method(
//           #saveToken,
//           [token],
//         ),
//         returnValue: _i9.Future<void>.value(),
//         returnValueForMissingStub: _i9.Future<void>.value(),
//       ) as _i9.Future<void>);

//   @override
//   _i9.Future<String?> getToken() => (super.noSuchMethod(
//         Invocation.method(
//           #getToken,
//           [],
//         ),
//         returnValue: _i9.Future<String?>.value(),
//       ) as _i9.Future<String?>);
// }
